### ISSUE TITLE
师傅好，请问这是直接能运行吗

### ISSUE THREAD

**Issue by 16ea** [WinMin/RHG-Server#1]
我试了下docker和ubuntu都不行，会报错
<img width="1283" alt="iShot_2023-04-17_20 13 41" src="https://user-images.githubusercontent.com/85932203/232480832-06a1c61d-1b84-47c4-8e0a-2a72d3691d97.png">

**Comment by WinMin** [comment]
因为他是需要访问接口的， 所以你应该先跑一下 test 目录下的测试文件

**Comment by winmin** [comment]
> 我试了下docker和ubuntu都不行，会报错 <img alt="iShot_2023-04-17_20 13 41" width="1283" src="https://user-images.githubusercontent.com/85932203/232480832-06a1c61d-1b84-47c4-8e0a-2a72d3691d97.png">


因为他是需要访问接口的， 所以你应该先跑一下 test 目录下的测试文件

**Comment by 16ea** [comment]
不好意思师傅，这样好像还是不行腻

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/85932203/232498461-12852879-e5da-405d-b66d-466ad6724f1c.png">

**Comment by 16ea** [comment]
不好意思师傅，这样好像还是不行腻
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/85932203/232498677-e54c7dcd-5285-468b-8053-27bd35f2d539.png">

**Comment by winmin** [comment]
> 不好意思师傅，这样好像还是不行腻 <img alt="image" width="1771" src="https://user-images.githubusercontent.com/85932203/232498677-e54c7dcd-5285-468b-8053-27bd35f2d539.png">

1. python3 tes_api.py
2. python3 myserver.py --host 127.0.0.1 --port 5001 --user admin --pass admin
3 . 访问 http://127.0.0.1:8080

**Comment by 16ea** [comment]
哦吼，可以了师傅，谢谢师傅指导
